version: "3.9"  
services:
  nest-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=campini
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
  
  nest-app:
    image: nest:1.0
    ports:
      - "3000:3000"
    depends_on:
      - nest-mysql
    restart: always
    
volumes:
  mysql_volume:

